### PR TITLE
OCAnnotation protocol, gitignore changes, user can use own AnnotationClass

### PR DESCRIPTION
**Pull request by XBeg9**
OCAnnotation protocol, gitignore changes, user can use own AnnotationClass

### CODE REVIEW

**Comment by XBeg9** [comment]
Also, I have added new podspec

**Comment by XBeg9** [comment]
Hey, will you review pull request?

**Comment by BotiKis** [comment]
Hi,

I'm not really happy with this protocol thingy although it's a cool idea.

Currently i'm redeveloping the whole project to become even faster and with support for animations after region changes. Since i also learned lot of new stuff since i started this project, i think a complete rewrite is the best thing.
I intend to extend the Annotation class with some features where a protocol won't be enough. Of course the api will stay the same.

So don't be mad at me but i will not merge this.

**Comment by XBeg9** [comment]
ok, I understand ;) Thanks for explaining.

**Pull request closed without merging**
