### PR TITLE
Improving performance by removing dynamicism of the coordinate property

### PR DESCRIPTION
**Pull request by marotan3**
See for my motivations my comment on commit: https://github.com/yinkou/OCMapView/commit/99438367ee00075b981be47d4d2103a5d39fc56b

To test the improvement: use the sample application in the simulator. hit "add 100 annotations" many times. After 1000 or so additions it gets slower, at around 5000 it takes seconds. Also, at 5000 annotations, grouping/ungrouping the clusters takes 4-5 seconds on my machine.

With this pull requests, adding 100 annotations has no noticeable slow down, and grouping/ungrouping clusters at 5000 annotates are nearly instantaneous

### CODE REVIEW

**Comment by gcasilva** [comment]
I want to give a positive feedback on this commit from marotan3, i tested the its improvements and the original algorithms, and his changes really improves the algorithm a lot. +1 for it being merged on the master.

**Comment by BotiKis** [comment]
Do what you wan't cause a pirate is free!

**Comment by gcasilva** [comment]
Sorry was that a joke yinkou? I appreciate the work you've done in sharing this library, i was just trying to help its development. Best regards.

**Comment by BotiKis** [comment]
Lol, don't be so serious, sure i was kidding. ;)  
I was referring to an old internet meme which itself has formed to an anthem for all pirates of the internet who has fought for online freedom.
https://www.youtube.com/watch?v=SLMJpHihykI

**Pull request merged**
